# Generated by Django 2.1 on 2018-09-01 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20180901_1936'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={},
        ),
    ]
