# Generated by Django 2.1 on 2018-09-01 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_auto_20180901_1938'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'permissions': (('can_create_auhor', 'Can create author aaaaa2'),)},
        ),
    ]
