# Generated by Django 2.1 on 2018-09-01 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_auto_20180901_1940'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'permissions': (('author_create', 'Can create author bibliotekars'),)},
        ),
    ]
