# Generated by Django 2.1 on 2018-09-01 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_auto_20180901_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.ManyToManyField(null=True, to='catalog.Language'),
        ),
    ]
