# Generated by Django 2.1 on 2018-09-01 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_auto_20180901_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='language',
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.ManyToManyField(null=True, to='catalog.Language'),
        ),
    ]
